services:
  app:
    build: .
    command: flask run --debug --host=0.0.0.0
    volumes:
      - "./src:/usr/src/"
    ports:
      - 5000:5000
    depends_on: 
      - db
    environment: 
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'data'
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080